version: '3.8'
services:
  db:
    container_name: postgis-13.3.1
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin-4
    image: dpage/pgadmin4
    depends_on: 
      - db
    ports:
      - "53603:53603"
      - "4000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@workstation.localhost
      PGADMIN_DEFAULT_PASSWORD: docker
volumes:
  pgdata: